services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gestlib_db
      POSTGRES_USER: gestlib_user
      POSTGRES_PASSWORD: gestlib_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gestlib_user -d gestlib_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_NAME=gestlib_db
      - DB_USER=gestlib_user
      - DB_PASSWORD=gestlib_password_2024
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-ux*g_2_&(iosifwh_50a!vy#j)s=5_uh_r3=oq64bf)r4xsw8x
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - SUPERUSER_USERNAME=superadmin
      - SUPERUSER_EMAIL=superadmin@gestlib.com
      - SUPERUSER_PASSWORD=SuperAdmin2024!
      - SUPERUSER_DNI=12345678
      - SUPERUSER_FULLNAME=Super Administrador del Sistema
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@gestlib.com
      - ADMIN_PASSWORD=Admin2024!
      - ADMIN_DNI=87654321
      - ADMIN_FULLNAME=Administrador de Biblioteca
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: